### ISSUE TITLE
ENH: file name in dtool readme edit

### ISSUE THREAD

**Issue by sannant** [jic-dtool/dtool-cli#3]
dtool readme edit opens a temporary file named "... .txt" with the default (or configured) editor. 
I suggest to change the extension to ".yml"  to trigger the correct linter in the editor.

**Comment by tjelvar-olsson** [comment]
This is a great idea. Thank you Antoine! :)

Fixed in dtool-create repo: https://github.com/jic-dtool/dtool-create/commit/ec676aa23021cb16ccab67da1fca3d055ba6551e

**Comment by tjelvar-olsson** [comment]
Released in: https://pypi.org/project/dtool-create/0.23.3/

**Comment by sannant** [comment]
Thank you for implementing it !
